services:
  - type: web
    name: ml-api
    runtime: docker
    build:
      dockerfile: Dockerfile
    env: python
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mlapi.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ml-api.onrender.com
      - key: PYTHONUNBUFFERED
        value: 1
    plan: starter
    healthCheckPath: /health/